// license:GPL2+
// copyright-holders:Felipe Sanches
/***************************************************************************

    KN6000 / KN6500 control panel HLE

    ONE device serves both models: their firmware button matrices are
    BYTE-IDENTICAL (compared descriptor-for-descriptor across all 30 segments
    and 164 button-bits -- zero differences). See notes/kn6000-panel-matrix.md.

    Where this matrix comes from
    ----------------------------
    The seg/bit GEOMETRY is extracted from the firmware itself: the
    PanelButtonDispatch descriptor arrays, reached through the pointer table at
    library 0x4C19BCAC (KN6000) / 0x4C19BDB0 (KN6500), consumed by the dispatcher
    at 0x4844D376 which indexes that table directly with the segment byte. Each
    12-byte entry is { u16 event, u16 class, u8 mask, u8 bit, u8 group, u8 flag,
    u32 handler }.

    The NAMES come from the SX-KN6000 service manual (pp.45-49), and the two
    sources agree cell-for-cell: all 150 populated button-bits in normSeg
    0x00-0x13 are accounted for, and every switch group the manual inventories
    (16 RHYTHM GROUP in 6/6/4 columns, 16 SOUND GROUP in 6/6/4, 32 MUTE UP/DOWN
    in four 8-tall columns, 6 PERFORMANCE PADS sharing three columns as 1/4, 2/5,
    3/6, 8 PANEL MEMORY, the CONDUCTOR and PART SELECT quads) lands exactly where
    the descriptors put it. That mutual confirmation is what makes this map
    trustworthy without a live sweep.

    Board split (service manual, confirmed by the descriptor content)
    ----------------------------------------------------------------
    Two Mitsubishi M37471M2196S sub-CPUs scan everything:
      IC1 on CPL -- 10 SEG columns -> normSeg 0x00-0x09, covering the CPL board
                    itself plus its matrix extensions LCDL and LCDC:
                      0x00-0x03 LCDL (RHYTHM GROUP, SOUND ARRANGER, APC, LCDL keys)
                      0x04-0x08 LCDC (32 MUTE UP/DOWN, PAGE/TR/HELP/HOLD/EXIT)
                      0x09      CPL  (PERFORMANCE PADS ops, MSA, VARIATION, DEMO)
      IC10 on CPR -- 16 SEG columns, 10 wired -> normSeg 0x0A-0x13, covering CPR
                    plus its extensions LCDR and CPC:
                      0x0A-0x0D LCDR (SOUND GROUP, SUSTAIN/DIGITAL EFFECT, LCDR keys)
                      0x0E-0x13 CPC + CPR (transport, effects, PANEL MEMORY, ...)
    A button is (SEG column x SW0..SW7 return line); an LED is (PNP anode group
    x SEG column). Note normSeg 0x12 is CPR SEG9, not SEG8: the manual finds CPR
    SEG8 unwired, and the firmware's normalized numbering skips it.

    Segments 0x14-0x1D exist in the descriptor table but are NOT panel buttons --
    they are the latched analog controls (the four pots at 0x16-0x19, the DATA
    dial at 0x1A) and pedal/rear switches, which reach the firmware through the
    base class's TYPE 2 control path rather than the switch-frame path.

    The CP wire protocol, ATN/RX handshake and analog controllers are shared with
    the KN7000 and live in the base class (kn_cpanel.cpp).

***************************************************************************/

#include "emu.h"
#include "kn6000_cpanel.h"

#define LOG_LEDS (1U << 4)

#define VERBOSE 0
#include "logmacro.h"

DEFINE_DEVICE_TYPE(KN6000_CPANEL, kn6000_cpanel_device, "kn6000_cpanel", "KN6000/KN6500 Control Panel HLE")

// The front-panel BUTTON matrix belongs to the panel sub-CPUs this device emulates, so the
// ports live HERE rather than in the driver's INPUT_PORTS. One port per sub-CPU scan column;
// each bit is one SW return line, forwarded unchanged (port index == normSeg, a pure identity).
static INPUT_PORTS_START(kn6000_cpanel)
	PORT_START("CPL_SEG0")   // normSeg 0x00 = CPL board scan column 0  (wire ADDR 0xC0)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PERFORMANCE PAD 1 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PERFORMANCE PAD 4 (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("8 & 16 BEAT (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("POP (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("BALLAD (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("ROK'N'ROLL & BLUES (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SOUL & FUNK (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MODERN DANCE (SW7)")
	PORT_START("CPL_SEG1")   // normSeg 0x01 = CPL board scan column 1  (wire ADDR 0xC1)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PERFORMANCE PAD 2 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PERFORMANCE PAD 5 (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("U.S. TRAD (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("COUNTRY (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("BIG BAND & SWING (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("JAZZ COMBO (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MARCH & WALTZ (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("BALLROOM & SHOW TIME (SW7)")
	PORT_START("CPL_SEG2")   // normSeg 0x02 = CPL board scan column 2  (wire ADDR 0xC2)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PERFORMANCE PAD 3 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PERFORMANCE PAD 6 (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LATIN (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("WORLD (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("CUSTOM (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MEMORY LOAD (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SOUND ARRANGER SET (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SOUND ARRANGER OFF/ON (SW7)")
	PORT_START("CPL_SEG3")   // normSeg 0x03 = CPL board scan column 3  (wire ADDR 0xC3)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("AUTO PLAY CHORD MODE (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("AUTO PLAY CHORD OFF/ON (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDL 1 (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDL 2 (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDL 3 (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDL 4 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDL 5 (SW7)")
	PORT_START("CPL_SEG4")   // normSeg 0x04 = CPL board scan column 4  (wire ADDR 0xC4)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 1 (PART 1 ON) (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 1 (PART 1 OFF) (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 2 (PART 2 ON) (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 2 (PART 2 OFF) (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 3 (PART 3 ON) (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 3 (PART 3 OFF) (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 4 (PART 4 ON) (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 4 (PART 4 OFF) (SW7)")
	PORT_START("CPL_SEG5")   // normSeg 0x05 = CPL board scan column 5  (wire ADDR 0xC5)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 5 (PART 5 ON) (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 5 (PART 5 OFF) (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 6 (PART 6 ON) (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 6 (PART 6 OFF) (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 7 (PART 7 ON) (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 7 (PART 7 OFF) (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 8 (PART 8 ON) (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 8 (PART 8 OFF) (SW7)")
	PORT_START("CPL_SEG6")   // normSeg 0x06 = CPL board scan column 6  (wire ADDR 0xC6)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 9 (PART 9 ON) (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 9 (PART 9 OFF) (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 10 (PART 10 ON) (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 10 (PART 10 OFF) (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 11 (PART 11 ON) (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 11 (PART 11 OFF) (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 12 (PART 12 ON) (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 12 (PART 12 OFF) (SW7)")
	PORT_START("CPL_SEG7")   // normSeg 0x07 = CPL board scan column 7  (wire ADDR 0xC7)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 13 (PART 13 ON) (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 13 (PART 13 OFF) (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 14 (PART 14 ON) (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 14 (PART 14 OFF) (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 15 (PART 15 ON) (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 15 (PART 15 OFF) (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE UP 16 (PART 16 ON) (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUTE DOWN 16 (PART 16 OFF) (SW7)")
	PORT_START("CPL_SEG8")   // normSeg 0x08 = CPL board scan column 8  (wire ADDR 0xC8)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PAGE UP (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PAGE DOWN (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("TR (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("HELP (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("DISPLAY HOLD (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("EXIT (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SOUND CONTROLLER MODE (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SOUND CONTROLLER RESET (SW7)")
	PORT_START("CPL_SEG9")   // normSeg 0x09 = CPL board scan column 9  (wire ADDR 0xC9)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PERFORMANCE PADS/BANK (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PERFORMANCE PADS/STOP (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PERFORMANCE PADS/AUTO SETTING (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUSIC STYLE ARRANGER (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("VARIATION & MSA 1 (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("VARIATION & MSA 2 (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("DEMO (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPR_SEG0")   // normSeg 0x0A = CPR board scan column 0  (wire ADDR 0x00)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PIANO (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("GUITAR (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("STRINGS & VOCAL (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("BRASS (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MALLET & ORCH PERC (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("WORLD (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPR_SEG1")   // normSeg 0x0B = CPR board scan column 1  (wire ADDR 0x01)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("ORGAN & ACCORDION (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SAX & WOODWIND (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PAD (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SYNTH (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("BASS (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("DRUM KITS (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPR_SEG2")   // normSeg 0x0C = CPR board scan column 2  (wire ADDR 0x02)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("DIGITAL DRAWBAR (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("ACCORDION REGISTER (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SOUND EXPLORER (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MEMORY (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SUSTAIN (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("DIGITAL EFFECT (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPR_SEG3")   // normSeg 0x0D = CPR board scan column 3  (wire ADDR 0x03)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SOUND DSP (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PART EFFECT VARIATION (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDR 1 (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDR 2 (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDR 3 (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDR 4 (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("LCDR 5 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_START("CPR_SEG4")   // normSeg 0x0E = CPR board scan column 4  (wire ADDR 0x04)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("ONE TOUCH PLAY (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SPLIT POINT (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("VARIATION & MSA 3 (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("VARIATION & MSA 4 (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PART SELECT LEFT (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PART SELECT RIGHT 2 (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PART SELECT RIGHT 1 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SOLO (SW7)")
	PORT_START("CPR_SEG5")   // normSeg 0x0F = CPR board scan column 5  (wire ADDR 0x05)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("FADE IN (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("FADE OUT (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("FILL IN 1 (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("FILL IN 2 (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("CONDUCTOR LEFT (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("CONDUCTOR RIGHT 2 (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("CONDUCTOR RIGHT 1 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("TECHNI-CHORD (SW7)")
	PORT_START("CPR_SEG6")   // normSeg 0x10 = CPR board scan column 6  (wire ADDR 0x06)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("INTRO & ENDING 1 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("INTRO & ENDING 2 (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("TAP TEMPO (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("START/STOP (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SEQUENCER PLAY (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SEQUENCER EASY REC (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PROGRAM MENU (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("DISK (SW7)")
	PORT_START("CPR_SEG7")   // normSeg 0x11 = CPR board scan column 7  (wire ADDR 0x07)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("TRANSPOSE - (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("TRANSPOSE + (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("R1/R2 OCTAVE - (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("R1/R2 OCTAVE + (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("GLOBAL EFFECT CHORUS (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("GLOBAL EFFECT MULTI (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("GLOBAL EFFECT REVERB (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("GLOBAL EFFECT MIC (SW7)")
	PORT_START("CPR_SEG8")   // normSeg 0x12 = CPR board scan column 8  (wire ADDR 0x08)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("MUSIC STYLIST (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("FAVORITES (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SYNCHRO & BREAK (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PANEL MEMORY SET (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("NEXT BANK (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("BANK VIEW (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("CUSTOM PANEL (SW7)")
	PORT_START("CPR_SEG9")   // normSeg 0x13 = CPR board scan column 9  (wire ADDR 0x09)
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PANEL MEMORY 1 (SW0)")
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PANEL MEMORY 2 (SW1)")
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PANEL MEMORY 3 (SW2)")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PANEL MEMORY 4 (SW3)")
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PANEL MEMORY 5 (SW4)")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PANEL MEMORY 6 (SW5)")
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PANEL MEMORY 7 (SW6)")
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("PANEL MEMORY 8 (SW7)")
INPUT_PORTS_END

ioport_constructor kn6000_cpanel_device::device_input_ports() const
{
	return INPUT_PORTS_NAME(kn6000_cpanel);
}


kn6000_cpanel_device::kn6000_cpanel_device(const machine_config &mconfig, const char *tag, device_t *owner, uint32_t clock) :
	kn_cpanel_base_device(mconfig, KN6000_CPANEL, tag, owner, clock),
	m_phys(*this, { "CPL_SEG0", "CPL_SEG1", "CPL_SEG2", "CPL_SEG3", "CPL_SEG4",
	                "CPL_SEG5", "CPL_SEG6", "CPL_SEG7", "CPL_SEG8", "CPL_SEG9",
	                "CPR_SEG0", "CPR_SEG1", "CPR_SEG2", "CPR_SEG3", "CPR_SEG4",
	                "CPR_SEG5", "CPR_SEG6", "CPR_SEG7", "CPR_SEG8", "CPR_SEG9" }),
	m_cpl_leds(*this, "cpl_led%u", 0U),
	m_cpr_leds(*this, "cpr_led%u", 0U)
{
}

// Reverse-normalization: normSeg -> CP wire ADDR. The KN6000 keeps the same two-bank
// wire allocation as the KN7000 -- the CPL-side sub-CPU answers on ADDRs 0xC0.., the
// CPR-side one on 0x00.. -- but with 10 columns each rather than the KN7000's 12 + 10.
// (That the wire encoding is shared is what makes the KN6000 accept panel traffic at all
// while running the KN7000's panel device, and is why its TEMPO/PROGRAM wheel already
// worked: only the matrix CONTENTS differ, not the transport.)
uint8_t kn6000_cpanel_device::seg_wire_addr(int seg) const
{
	return (seg < 0x0a) ? uint8_t(0xc0 + seg)          // normSeg 0x00-0x09 -> CPL ADDR 0xC0-0xC9
	                    : uint8_t(seg - 0x0a);         // normSeg 0x0A-0x13 -> CPR ADDR 0x00-0x09
}

// One decoded LED-command frame. ADDR = board (bit 7:6 clear = CPR, set = CPL) | LED
// register; each DATA bit is one LED at index reg*8 + bit within that board's bank.
//
// The service manual inventories every LED by designator, colour and legend (CPL D125-D130,
// LCDL D101-D134, LCDC D106, LCDR D301-D320, CPC D323-D345, CPR D351-D377) -- that table is
// reproduced in notes/kn6000-panel-matrix.md. What it does NOT give without further wire
// tracing is the anode-group x SEG coordinate for most of them, i.e. which register/bit the
// firmware uses. So this is a faithful GENERIC decode onto cpl_led#/cpr_led# outputs: the
// firmware's LED writes land on stable, correctly-banked output names. Binding individual
// D-numbers to legends is deferred until a KN6000 .lay exists to display them (there is none
// yet), at which point the manual's inventory plus the built-in "Panel SW & LED test"
// (service manual p.22 section 7.5) gives the ground truth to bind against.
void kn6000_cpanel_device::panel_led_frame(uint8_t addr, uint8_t data)
{
	const int reg = addr & 0x3f;
	output_finder<512> &bank = ((addr & 0xc0) == 0) ? m_cpr_leds : m_cpl_leds;
	for (int bit = 0; bit < 8; bit++)
	{
		const int led = reg * 8 + bit;
		if (led < 512)
			bank[led] = BIT(data, bit);
	}
	LOGMASKED(LOG_LEDS, "panel LED frame addr=%02X data=%02X\n", addr, data);
}
