#!/usr/bin/env python3
"""Generate the per-rig index for tools/rigs/, and audit the rigs' headers.

WHY: tools/rigs/README.md is a good hand-written guide, but it names only 13 of the 109
rigs individually -- the other 96 are reachable only through a "by family" table, so
finding the rig that answers a given question means grepping. This regenerates a table
covering every rig from its own header comment.

It also reports what the README's honesty note asserted but never measured:

  * rigs with NO description at all
  * rigs whose header names a DIFFERENT script than the file it sits in (copy-paste rot)
  * rigs with no runnable command documented

    python3 tools/gen_rig_index.py            # audit only, prints counts
    python3 tools/gen_rig_index.py --write    # rewrite the generated section of README.md

The generated section is delimited by the two markers below; everything outside them is
hand-written and is never touched.
"""
import argparse
import pathlib
import re
import sys

BEGIN = "<!-- BEGIN GENERATED RIG INDEX -- edit via tools/gen_rig_index.py -->"
END = "<!-- END GENERATED RIG INDEX -->"

RIGS = pathlib.Path(__file__).resolve().parent / "rigs"
README = RIGS / "README.md"


def header(path):
    """The leading comment block, as a list of stripped lines."""
    out = []
    for line in path.read_text(errors="replace").splitlines():
        if not line.startswith("--"):
            if out:
                break
            continue
        out.append(line[2:].strip())
    return out


def describe(path):
    """One-line description: the text after 'name.lua --' on the first line, else the
    first non-empty comment line that is not a command or a marker."""
    h = header(path)
    if not h:
        return None, None
    first = h[0]
    m = re.match(r"^(\S+\.lua)\s*--+\s*(.+)$", first)
    if m:
        return m.group(1), m.group(2).strip()
    for line in h:
        if not line or line.startswith(("rig-machine:", "./", "Usage")) or line.startswith("⚠"):
            continue
        return None, line.strip()
    return None, None


def command(path):
    for line in header(path):
        if "rig.sh" in line:
            return line.strip()
    return None


def machine(path, stem):
    for line in header(path):
        m = re.match(r"^rig-machine:\s*([a-z0-9]+)", line)
        if m:
            return m.group(1), "declared"
    for pre, mach in (("kn5000", "kn5000"), ("kn6500", "kn6500"), ("kn6_", "kn6000"),
                      ("kn6000", "kn6000"), ("kn24_", "kn2400"), ("kn2400", "kn2400"),
                      ("kn2600", "kn2600"), ("kn1500", "kn1500")):
        if stem.startswith(pre):
            return mach, "guessed"
    return "kn7000", "default"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true", help="rewrite the generated section")
    args = ap.parse_args()

    rows, no_desc, mismatch, no_cmd = [], [], [], []
    for p in sorted(RIGS.glob("*.lua")):
        claimed, desc = describe(p)
        mach, how = machine(p, p.stem)
        if claimed and claimed != p.name:
            mismatch.append((p.name, claimed))
        if not desc:
            no_desc.append(p.name)
        if not command(p):
            no_cmd.append(p.name)
        rows.append((p.stem, mach, how, desc or "—", bool(command(p))))

    print(f"rigs: {len(rows)}")
    print(f"  no description        : {len(no_desc)}")
    print(f"  header names another  : {len(mismatch)}"
          + (f"  {mismatch}" if mismatch else ""))
    print(f"  no runnable command   : {len(no_cmd)}")
    print(f"  machine declared      : {sum(1 for r in rows if r[2] == 'declared')}")

    if not args.write:
        return 0

    out = [BEGIN, "", "## Every rig", "",
           f"Generated by `tools/gen_rig_index.py` from each rig's own header — {len(rows)} rigs. "
           "Run any of them with `./tools/rig.sh <rig>`.", "",
           "The **machine** column is what `rig.sh` will pick: *declared* comes from a "
           "`-- rig-machine:` header and is trustworthy; *guessed* is inferred from the filename; "
           "*default* means nothing indicated a model and it falls back to kn7000. "
           "A guessed or defaulted rig pointed at the wrong driver still runs and still "
           "produces output — pass the machine explicitly when in doubt.", "",
           "| rig | machine | ✔ | what question it answers |", "|---|---|---|---|"]
    for stem, mach, how, desc, has_cmd in rows:
        mark = {"declared": "", "guessed": " *(guessed)*", "default": " *(default)*"}[how]
        desc = desc.replace("|", "\\|")
        if len(desc) > 150:
            desc = desc[:147] + "…"
        out.append(f"| `{stem}` | {mach}{mark} | {'✔' if has_cmd else ''} | {desc} |")
    out += ["",
            "**✔** = the header documents a runnable `rig.sh` command. "
            f"{sum(1 for r in rows if r[4])} of {len(rows)} do; the rest still need one.",
            "", END]

    text = README.read_text()
    block = "\n".join(out)
    if BEGIN in text and END in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    README.write_text(text)
    print(f"wrote {README}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
