#!/usr/bin/env python3
"""Generate src/mame/layout/kn7000.lay from the driver's INPUT_PORTS.

This emits a *functional* MAME layout for the KN7000: the emulated LCD screen,
every declared front-panel button as a clickable, labelled key (bound to its
ioport bit), and a per-board strip of LEDs bound to the driver's output finders
(cpl_led/cpc_led/cpr_led).

The button-to-LED physical placement is not yet known precisely (the LED-command
ADDR->silk-screen map is still provisional -- see notes/panel-serial-protocol.md),
so buttons are laid out board-by-board as a segment x bit grid and the LEDs as a
labelled strip. Placement can later be refined against the service-manual artwork
without changing the bindings. Re-run after editing the driver's INPUT_PORTS:

    python3 tools/gen_layout.py
"""
import re
import sys
import os

DRIVER = os.path.join(os.path.dirname(__file__), "..", "src", "mame", "matsushita", "kn7000.cpp")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "mame", "layout", "kn7000.lay")


def parse_ports(text):
    """Return ordered dict {port: [(mask, name), ...]} from INPUT_PORTS_START(kn7000)."""
    m = re.search(r"INPUT_PORTS_START\(kn7000\)(.*?)INPUT_PORTS_END", text, re.S)
    if not m:
        sys.exit("could not find INPUT_PORTS_START(kn7000)")
    body = m.group(1)
    ports = {}
    cur = None
    for line in body.splitlines():
        ps = re.search(r'PORT_START\("([^"]+)"\)', line)
        if ps:
            cur = ps.group(1)
            ports[cur] = []
            continue
        pb = re.search(r"PORT_BIT\(\s*(0x[0-9a-fA-F]+)", line)
        if pb and cur is not None:
            nm = re.search(r'PORT_NAME\("([^"]+)"\)', line)
            name = nm.group(1) if nm else ""
            ports[cur].append((int(pb.group(1), 16), name))
    return ports


def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;"))


# ---- geometry ----
CELL_W, CELL_H, GAP = 96, 26, 4
SCREEN_W, SCREEN_H = 320, 240
BOARDS = [
    ("CPL", "cpl_led", [f"CPL_SEG{i}" for i in range(8)]),
    ("CPC", "cpc_led", [f"CPC_SEG{i}" for i in range(5)]),
    ("CPR", "cpr_led", [f"CPR_SEG{i}" for i in range(10)]),
]


def main():
    text = open(DRIVER).read()
    ports = parse_ports(text)

    ncols = sum(len(segs) for _, _, segs in BOARDS)   # 8+5+10 = 23
    canvas_w = GAP + ncols * (CELL_W + GAP)
    board_top = SCREEN_H + 80
    canvas_h = board_top + 8 * (CELL_H + GAP) + 90

    out = []
    w = out.append
    w('<?xml version="1.0"?>')
    w('<!-- license:CC0-1.0 -->')
    w('<!-- GENERATED by tools/gen_layout.py from kn7000.cpp INPUT_PORTS; do not edit by hand. -->')
    w('<mamelayout version="2">')
    w('')
    # LED elements
    w('\t<element name="grn_led" defstate="0">')
    w('\t\t<disk state="1"><color red="0.1" green="1.0" blue="0.2"/></disk>')
    w('\t\t<disk state="0"><color red="0.0" green="0.22" blue="0.05"/></disk>')
    w('\t</element>')
    w('\t<element name="red_led" defstate="0">')
    w('\t\t<disk state="1"><color red="1.0" green="0.15" blue="0.1"/></disk>')
    w('\t\t<disk state="0"><color red="0.22" green="0.03" blue="0.0"/></disk>')
    w('\t</element>')
    w('\t<element name="panel_bg"><rect><color red="0.11" green="0.11" blue="0.12"/></rect></element>')
    for bname, _, _ in BOARDS:
        w(f'\t<element name="title_{bname}">')
        w('\t\t<rect><color red="0.05" green="0.05" blue="0.06"/></rect>')
        w(f'\t\t<text string="{bname} board"><color red="0.8" green="0.8" blue="0.85"/></text>')
        w('\t</element>')
    w('')

    # one labelled, pressable button element per (port,bit) that has a name
    def btn_elem(port, mask):
        return f"btn_{port}_{mask:02x}"

    for port, bits in ports.items():
        if not port.startswith(("CPL_", "CPC_", "CPR_")):
            continue
        for mask, name in bits:
            en = btn_elem(port, mask)
            label = esc(name) if name else f"{port}.{mask:02x}"
            w(f'\t<element name="{en}" defstate="0">')
            w('\t\t<rect state="0"><color red="0.20" green="0.20" blue="0.23"/></rect>')
            w('\t\t<rect state="1"><color red="0.65" green="0.55" blue="0.12"/></rect>')
            w(f'\t\t<text string="{label}"><color red="0.92" green="0.92" blue="0.92"/>'
              '<bounds x="0.03" y="0.18" width="0.94" height="0.64"/></text>')
            w('\t</element>')
    w('')

    # ---- view ----
    w('\t<view name="Control Panel">')
    w(f'\t\t<element ref="panel_bg"><bounds x="0" y="0" width="{canvas_w}" height="{canvas_h}"/></element>')
    # screen centred at top
    sx = (canvas_w - SCREEN_W) // 2
    w(f'\t\t<screen index="0"><bounds x="{sx}" y="30" width="{SCREEN_W}" height="{SCREEN_H}"/></screen>')

    # boards left-to-right, each a segment(column) x bit(row) grid
    col = 0
    for bname, ledpfx, segs in BOARDS:
        x0 = GAP + col * (CELL_W + GAP)
        bw = len(segs) * (CELL_W + GAP)
        # board title
        w(f'\t\t<element ref="title_{bname}"><bounds x="{x0}" y="{board_top - 40}" '
          f'width="{bw - GAP}" height="26"/></element>')
        for si, seg in enumerate(segs):
            cx = GAP + (col + si) * (CELL_W + GAP)
            for bit in range(8):
                mask = 1 << bit
                # find a button with this mask
                names = [n for (m, n) in ports.get(seg, []) if m == mask]
                if not names:
                    continue
                cy = board_top + bit * (CELL_H + GAP)
                en = btn_elem(seg, mask)
                w(f'\t\t<element ref="{en}" inputtag="{seg}" inputmask="0x{mask:02x}">'
                  f'<bounds x="{cx}" y="{cy}" width="{CELL_W}" height="{CELL_H}"/></element>')
        col += len(segs)

    # LED strips per board along the bottom
    led_y = board_top + 8 * (CELL_H + GAP) + 20
    lx = GAP
    for bname, ledpfx, segs in BOARDS:
        count = {"cpl_led": 64, "cpc_led": 64, "cpr_led": 80}[ledpfx]
        per_row = 32
        for i in range(count):
            r = i // per_row
            c = i % per_row
            x = lx + c * 12
            y = led_y + r * 12
            w(f'\t\t<element name="{ledpfx}{i}" ref="grn_led">'
              f'<bounds x="{x}" y="{y}" width="7" height="7"/></element>')
        lx += (per_row * 12) + 30

    w('\t</view>')
    w('</mamelayout>')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    nbtn = sum(len([1 for _ in bits]) for p, bits in ports.items()
               if p.startswith(("CPL_", "CPC_", "CPR_")))
    print(f"wrote {OUT}: {nbtn} buttons, canvas {canvas_w}x{canvas_h}")


if __name__ == "__main__":
    main()
