#!/usr/bin/env python3
"""genre_truth.py -- ground-truth verifier for the KN7000 built-in style-name lists.

Decides, byte-precisely and offline, how every factory genre slot resolves through
the "Technics Rhythms" resource name resolver (prog 0x48433AC4), for BOTH:
 (1) the ORIGINAL intact nametable inside the truncated resource copy that the
     dumped table ROM carries at file offset 0x3E828C, and
 (2) the INSTALLED synthetic resource (kn7000_rhythms_synthetic.rom, generated by
     tools/gen_technics_rhythms.py, mapped at 0x54E00000),
then compares the two and prints per-genre truth tables + a summary.

Written 2026-07-19 to falsify the "off-by-one shifted the 52-name window"
hypothesis after Felipe's genre-screen report. VERDICT (see
notes/rhythm-name-list-bug.md and notes/genre-name-ground-truth.txt): NO BUG.
The firmware's own nametable assigns the 52 secondary (real-name) entries as
C&W slots 2-14 (13) + March&Waltz 1-12 (12) + Latin&World 1-26 (26) + 60s&70s
slot 1 (1, "70s Orchestra"); C&W slot 1 is a plain LOCAL record whose name lives
only on the undumped ~4.1MB rhythm flash. Original and synthetic resolve
class+index IDENTICALLY for all 220 factory IDs.

Resolver semantics (from code 0x48433AC4, see
notes/sequenced-playback-and-style-data-rootcause.md):
  idx   = ((id & 0xF00) >> 1) | (id & 0x7F)          [verified 220/220]
  e     = u16BE(nametable + 2*idx)                    [nametable = dir+0x33]
  e & 0xC000 == 0x8000 -> one indirection: e = u16BE(nametable + 2*(e&0x7FF))
  e < count (0xDD)     -> LOCAL record: name = 13 bytes at dir + u24BE(sub+3*e)
  e & 0xC000 == 0x4000 -> SECONDARY: i2 = e & 0x3FFF, name = 13 bytes at
                          SEC + u24BE(SEC + 3*i2), SEC = table ROM file 0x244F78
                          (INTACT in the dump; the firmware reads it directly)

Inputs (see --help for overrides):
  --table  dumped table ROM (kn7000_table.rom)
  --prog   decompressed program image (base 0x48400000); genre table @0x48735EE4
  --synth  installed kn7000_rhythms_synthetic.rom
  --full   optional full table-ROM rebuild for a cross-image sanity check
"""
import argparse
import sys

COPY_OFF = 0x3E828C          # truncated "Technics Rhythms" copy in table ROM
SEC_OFF = 0x244F78           # intact secondary subtable in table ROM
GENRE_TABLE = 0x335EE4       # prog file offset of genre table (0x48735EE4)
GENRE_COUNT_OFF = 0x336064
HDR_PTR, NT_PTR, SUB_PTR = 0x18, 0x1B, 0x1E

def u16be(b, o): return (b[o] << 8) | b[o + 1]
def u24be(b, o): return (b[o] << 16) | (b[o + 1] << 8) | b[o + 2]
def u16le(b, o): return b[o] | (b[o + 1] << 8)
def u32le(b, o): return b[o] | (b[o+1] << 8) | (b[o+2] << 16) | (b[o+3] << 24)

def style_index(sid):
    return ((sid & 0xF00) >> 1) | (sid & 0x7F)

def read_genres(prog):
    n = u16le(prog, GENRE_COUNT_OFF)
    out = []
    for g in range(n):
        o = GENRE_TABLE + g * 0x18
        name = prog[o:o+16].decode("latin1").strip()
        cnt = prog[o + 0x11]
        lst = u32le(prog, o + 0x14) - 0x48400000
        ids = [u32le(prog, lst + 4*i) for i in range(cnt)]
        out.append((name, ids))
    return out

def sec_name(table, i2):
    off = SEC_OFF + u24be(table, SEC_OFF + 3 * i2)
    return table[off:off+13].decode("latin1")

def classify(img, base, table, sid):
    """Byte-exact resolver 0x48433AC4 against resource image `img` rooted at
    file offset `base`. Returns (idx, raw entry, chain, class, index, name)."""
    hdr = u24be(img, base + HDR_PTR)
    count = u16be(img, base + hdr + 2)
    nt = base + u24be(img, base + NT_PTR)
    sub = base + u24be(img, base + SUB_PTR)
    idx = style_index(sid)
    e0 = u16be(img, nt + 2 * idx)
    chain = [e0]
    e = e0
    if (e & 0xC000) == 0x8000:               # one indirection
        e = u16be(img, nt + 2 * (e & 0x7FF))
        chain.append(e)
    if e < count:
        off = base + u24be(img, sub + 3 * e)
        nm = img[off:off+13].decode("latin1", "replace")
        return idx, e0, chain, "LOCAL", e, nm
    if (e & 0xC000) == 0x4000:
        i2 = e & 0x3FFF
        return idx, e0, chain, "SECONDARY", i2, sec_name(table, i2)
    return idx, e0, chain, "UNRESOLVED", e, None

def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--table", default="/home/fsanches/compartilhado/kn7000-emulator/roms/kn7000/kn7000_table.rom")
    ap.add_argument("--prog", default="/home/fsanches/compartilhado/kn7000_scratchpad_snapshot/kn7000_program_decompressed.bin")
    ap.add_argument("--synth", default="/home/fsanches/compartilhado/kn7000-emulator/roms/kn7000/kn7000_rhythms_synthetic.rom")
    ap.add_argument("--full", default=None, help="optional full table-ROM image for a sanity cross-check")
    ap.add_argument("--out", default=None, help="also write the report to this file")
    args = ap.parse_args()

    table = open(args.table, "rb").read()
    prog = open(args.prog, "rb").read()
    synth = open(args.synth, "rb").read()
    tfull = open(args.full, "rb").read() if args.full else None

    out = []
    def p(s=""):
        out.append(s)
        print(s)

    # -- sanity: the two table images agree where we read them ----------------
    assert table[COPY_OFF:COPY_OFF+16] == b"Technics Rhythms", "copy magic"
    assert synth[0:16] == b"Technics Rhythms", "synthetic magic"
    if tfull:
        assert tfull[COPY_OFF:COPY_OFF+0x1248] == table[COPY_OFF:COPY_OFF+0x1248], \
            "full image disagrees with the table ROM at the copy"
        assert tfull[SEC_OFF:SEC_OFF+0x400] == table[SEC_OFF:SEC_OFF+0x400], \
            "full image disagrees at the secondary subtable"
        p("[sanity] full image == table ROM at copy+secondary  OK")

    # directory geometry of both images
    for tag, img, base in (("ORIGINAL copy @table+0x3E828C", table, COPY_OFF),
                           ("SYNTHETIC ROM @0x0", synth, 0)):
        hdr = u24be(img, base + HDR_PTR)
        count = u16be(img, base + hdr + 2)
        nt = u24be(img, base + NT_PTR)
        sub = u24be(img, base + SUB_PTR)
        p(f"[geometry] {tag}: hdr=+{hdr:#x} count={count:#x} nt=+{nt:#x} sub=+{sub:#x}")

    # nametable byte-compare original vs synthetic (0x800 entries u16BE)
    nt_o = COPY_OFF + u24be(table, COPY_OFF + NT_PTR)
    nt_s = u24be(synth, NT_PTR)
    same_nt = table[nt_o:nt_o+0x1000] == synth[nt_s:nt_s+0x1000]
    p(f"[nametable] original vs synthetic verbatim: {'IDENTICAL' if same_nt else '*** DIFFER ***'}")
    if not same_nt:
        for i in range(0x800):
            a = u16be(table, nt_o + 2*i); b = u16be(synth, nt_s + 2*i)
            if a != b:
                p(f"    first diff at nt idx {i:#x}: orig {a:#06x} synth {b:#06x}")
                break
    # subtable compare (169+8 u24BE entries)
    sub_o = COPY_OFF + u24be(table, COPY_OFF + SUB_PTR)
    sub_s = u24be(synth, SUB_PTR)
    same_sub = table[sub_o:sub_o+(169+8)*3] == synth[sub_s:sub_s+(169+8)*3]
    p(f"[subtable]  original vs synthetic verbatim: {'IDENTICAL' if same_sub else '*** DIFFER ***'}")

    # -- the 52 secondary names, indexed ---------------------------------------
    p()
    p("== SECONDARY catalog (table ROM 0x244F78, INTACT) ==")
    for i in range(52):
        p(f"  sec[{i:#04x}] = {sec_name(table, i)!r}")

    # -- per-genre truth tables ------------------------------------------------
    genres = read_genres(prog)
    p()
    p("=" * 100)
    p("PER-GENRE TABLES: (1) ORIGINAL intact nametable ground truth  vs  (2) SYNTHETIC ROM resolution")
    p("class key: LOCAL n = plain local record n (name lives in undumped rhythm flash ->")
    p("           placeholder in synthetic)   SECONDARY n = secondary catalog index n (REAL name)")
    p("=" * 100)

    tot = {"SECONDARY": 0, "LOCAL": 0, "OTHER": 0}
    sec_by_genre = {}
    divergences = []
    for gname, ids in genres:
        p()
        p(f"-- {gname} ({len(ids)} slots) --")
        p(f"   {'slot':4s} {'styleID':>8s} {'idx':>5s} {'entry':>6s}  {'ORIGINAL class':<22s} {'orig name (if real)':<16s} | SYNTH resolves to")
        nsec = 0
        for slot, sid in enumerate(ids, 1):
            if sid & 0x300000:
                p(f"   {slot:<4d} 0x{sid:06X}  (CUSTOM/MEMORY: RAM path, not in this resource)")
                continue
            idx, e0, chain, cls, ci, nm = classify(table, COPY_OFF, table, sid)
            idx2, e02, chain2, cls2, ci2, nm2 = classify(synth, 0, table, sid)
            assert (idx, e0, chain) == (idx2, e02, chain2), "nametable mismatch mid-resolve"
            ch = "->".join(f"{x:04x}" for x in chain)
            oname = nm if cls == "SECONDARY" else ""
            p(f"   {slot:<4d} 0x{sid:06X}  {idx:04x}  {ch:>9s}  {cls:<10s}{ci:<4d}{'':8s} {oname:<16s} | {cls2:<10s}{ci2:<4d} {nm2!r}")
            tot[cls if cls in tot else "OTHER"] += 1
            if cls == "SECONDARY":
                nsec += 1
            if cls != cls2 or ci != ci2:
                divergences.append((gname, slot, sid, cls, ci, cls2, ci2))
        sec_by_genre[gname] = nsec

    p()
    p("== SUMMARY ==")
    p(f"totals over factory (non-RAM) IDs: SECONDARY={tot['SECONDARY']}  LOCAL={tot['LOCAL']}  other={tot['OTHER']}")
    p("secondary (REAL-name) slots per genre:")
    for g, n in sec_by_genre.items():
        if n:
            p(f"   {g:<18s} {n}")
    p()
    if divergences:
        p("*** ORIGINAL vs SYNTHETIC class divergences (bug evidence): ***")
        for d in divergences:
            p(f"   {d}")
    else:
        p("ORIGINAL vs SYNTHETIC: class+index IDENTICAL for every slot (no shift, no off-by-one).")

    p()
    p("== VERDICT vs Felipe's observation ==")
    cw = [g for g in sec_by_genre if "COUNTRY" in g.upper()]
    s67 = [g for g in sec_by_genre if "60" in g]
    lat = [g for g in sec_by_genre if "LATIN" in g.upper()]
    mw = [g for g in sec_by_genre if "MARCH" in g.upper() or "WALTZ" in g.upper()]
    p(f"   LATIN&WORLD secondary count: {[sec_by_genre[g] for g in lat]}")
    p(f"   MARCH&WALTZ secondary count: {[sec_by_genre[g] for g in mw]}")
    p(f"   COUNTRY&W   secondary count: {[sec_by_genre[g] for g in cw]}")
    p(f"   60s&70s     secondary count: {[sec_by_genre[g] for g in s67]}")

    if args.out:
        with open(args.out, "w") as f:
            f.write("\n".join(out) + "\n")
        print(f"\nwrote {args.out}")

if __name__ == "__main__":
    sys.exit(main())
